# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-05 02:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0002_auto_20161105_0111'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableMoney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.CharField(choices=[('JAN', '一月'), ('FEB', '二月'), ('MAR', '三月'), ('APR', '四月'), ('MAY', '五月'), ('JUN', '六月'), ('JUL', '七月'), ('AUG', '八月'), ('SEP', '九月'), ('OCT', '十月'), ('NOV', '十一月'), ('DEC', '十二月')], max_length=20)),
                ('day_price', models.IntegerField()),
                ('totle_price', models.IntegerField()),
                ('holiday_count', models.IntegerField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.UserProfile')),
            ],
        ),
    ]
