# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-05 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablemoney', '0003_auto_20161105_0220'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
