# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-05 02:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tablemoney', '0004_monthyear'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablemoney',
            name='year',
        ),
        migrations.AddField(
            model_name='monthyear',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthyear',
            name='month',
            field=models.CharField(blank=True, choices=[('JAN', '一月'), ('FEB', '二月'), ('MAR', '三月'), ('APR', '四月'), ('MAY', '五月'), ('JUN', '六月'), ('JUL', '七月'), ('AUG', '八月'), ('SEP', '九月'), ('OCT', '十月'), ('NOV', '十一月'), ('DEC', '十二月')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tablemoney',
            name='month',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tablemoney.MonthYear'),
        ),
    ]
