# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-05 03:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablemoney', '0006_auto_20161105_0303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablemoney',
            old_name='holiday_count',
            new_name='workday_count',
        ),
    ]
