# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-05 03:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablemoney', '0008_auto_20161105_0338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlytotal',
            old_name='MonthlyTotal',
            new_name='monthlytotal',
        ),
    ]
