# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-05 05:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tablemoney', '0011_auto_20161105_0500'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(blank=True, choices=[('一月', '一月'), ('二月', '二月'), ('三月', '三月'), ('四月', '四月'), ('五月', '五月'), ('六月', '六月'), ('七月', '七月'), ('八月', '八月'), ('九月', '九月'), ('十月', '十月'), ('十一月', '十一月'), ('十二月', '十二月')], max_length=20, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tablemoney',
            name='month',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tablemoney.Month'),
        ),
        migrations.DeleteModel(
            name='MonthlyTotal',
        ),
    ]
