# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-05 06:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tablemoney', '0013_month_month_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='month',
            field=models.CharField(choices=[('一月', '一月'), ('二月', '二月'), ('三月', '三月'), ('四月', '四月'), ('五月', '五月'), ('六月', '六月'), ('七月', '七月'), ('八月', '八月'), ('九月', '九月'), ('十月', '十月'), ('十一月', '十一月'), ('十二月', '十二月')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tablemoney',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablemoney.Month'),
        ),
    ]
