# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-06 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablemoney', '0016_auto_20161106_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='month',
            field=models.CharField(choices=[('jan', '一月'), ('feb', '二月'), ('mar', '三月'), ('apr', '四月'), ('may', '五月'), ('jun', '六月'), ('jul', '七月'), ('aug', '八月'), ('sep', '九月'), ('oct', '十月'), ('nov', '十一月'), ('dec', '十二月')], max_length=20),
        ),
    ]
