# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-06 02:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tablemoney', '0018_auto_20161106_0126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='month',
            name='year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablemoney.Year'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tablemoney',
            name='year',
            field=models.ForeignKey(default=2016, on_delete=django.db.models.deletion.CASCADE, to='tablemoney.Year'),
            preserve_default=False,
        ),
    ]
