# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-06 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20161105_0331'),
        ('tablemoney', '0019_auto_20161106_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='year',
            name='name',
            field=models.ManyToManyField(through='tablemoney.TableMoney', to='userprofile.UserProfile'),
        ),
    ]
