# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-06 07:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tablemoney', '0028_auto_20161106_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablemoney',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.UserProfile'),
        ),
        migrations.AlterField(
            model_name='tablemoney',
            name='payee',
            field=models.ManyToManyField(blank=True, related_name='payee', to='userprofile.UserProfile'),
        ),
    ]
