# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-11 01:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablemoney', '0029_auto_20161106_0728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablemoney',
            name='payee',
        ),
    ]
