# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-11 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_payee'),
        ('tablemoney', '0030_remove_tablemoney_payee'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablemoney',
            name='payee',
            field=models.ManyToManyField(blank=True, related_name='payee', to='userprofile.UserProfile'),
        ),
    ]
