# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-11 02:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablemoney', '0031_tablemoney_payee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='month',
            options={'ordering': ['-pk']},
        ),
    ]
