# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-11 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablemoney', '0032_auto_20161111_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablemoney',
            name='note',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
