# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-11 05:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablemoney', '0033_tablemoney_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tablemoney',
            options={'ordering': ['name']},
        ),
    ]
