# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-12 01:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_auto_20161112_0950'),
        ('tablemoney', '0035_auto_20161111_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablemoney',
            name='test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userprofile.Payee'),
            preserve_default=False,
        ),
    ]
