# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-12 02:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tablemoney', '0036_tablemoney_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablemoney',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.Payee'),
        ),
    ]
