# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-12 02:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0009_auto_20161112_1006'),
        ('tablemoney', '0037_auto_20161112_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablemoney',
            name='test',
        ),
        migrations.RemoveField(
            model_name='tablemoney',
            name='payee',
        ),
        migrations.AddField(
            model_name='tablemoney',
            name='payee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.Payee'),
        ),
    ]
