# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-13 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablemoney', '0038_auto_20161112_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='current_money',
            field=models.IntegerField(default=0),
        ),
    ]
