# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-13 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablemoney', '0039_month_current_money'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablemoney',
            name='day_price',
        ),
        migrations.AddField(
            model_name='tablemoney',
            name='member_day_price',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='tablemoney',
            name='substitute_day_price',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='month',
            name='month',
            field=models.CharField(choices=[('一月', '一月'), ('二月', '二月'), ('三月', '三月'), ('四月', '四月'), ('五月', '五月'), ('六月', '六月'), ('七月', '七月'), ('八月', '八月'), ('九月', '九月'), ('十月', '十月'), ('十一月', '十一月'), ('十二月', '十二月')], max_length=20, unique=True),
        ),
    ]
