# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-13 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablemoney', '0042_auto_20161113_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablemoney',
            name='day_price',
        ),
        migrations.AddField(
            model_name='tablemoney',
            name='member_day_price',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='tablemoney',
            name='substitute_day_price',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
