# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-15 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablemoney', '0044_auto_20161113_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
