# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-15 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablemoney', '0045_auto_20161115_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
