# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-17 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablemoney', '0046_auto_20161115_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablemoney',
            name='year',
            field=models.CharField(default=105, max_length=20),
            preserve_default=False,
        ),
    ]
