# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-17 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablemoney', '0048_auto_20161117_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='year',
            field=models.PositiveIntegerField(default=105),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tablemoney',
            name='year',
            field=models.PositiveIntegerField(),
        ),
    ]
