# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-21 06:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tablemoney', '0055_auto_20161121_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_money_month', to='holiday.HolidayMonth'),
        ),
    ]
