# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-22 00:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablemoney', '0058_tablemoney_identify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablemoney',
            name='identify',
        ),
    ]
