# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-29 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablemoney', '0061_auto_20161129_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablemoney',
            name='pay_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
