# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-24 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablemoney', '0062_auto_20161129_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablemoney',
            name='pay_date',
            field=models.CharField(blank=True, default=1, max_length=20),
            preserve_default=False,
        ),
    ]
