# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0012_userprofile_eat'),
        ('tablemoney', '0063_auto_20161224_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraTableMoney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('extra_price', models.PositiveIntegerField()),
                ('identify', models.CharField(max_length=20)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablemoney.Month')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.UserProfile')),
            ],
        ),
    ]
