# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablemoney', '0064_extratablemoney'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extratablemoney',
            name='identify',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
