# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-24 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import train.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZhuDi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ZhuDiTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('img', models.FileField(upload_to=train.models.upload_location)),
                ('img2', models.FileField(upload_to=train.models.upload_location)),
                ('img3', models.FileField(blank=True, upload_to=train.models.upload_location)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train.ZhuDi')),
            ],
        ),
        migrations.CreateModel(
            name='ZuXun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ZuXunTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('img', models.FileField(upload_to='')),
                ('session', models.ManyToManyField(to='train.ZuXun')),
            ],
        ),
    ]
