# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-25 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0002_auto_20161225_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zuxuntable',
            name='img',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='zuxuntable',
            name='img2',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='zuxuntable',
            name='img3',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
