# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-25 09:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0006_auto_20161225_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zhuditable',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train.ZhuDi'),
        ),
        migrations.AlterField(
            model_name='zuxuntable',
            name='session',
            field=models.CharField(max_length=50),
        ),
    ]
