# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-02 00:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0007_auto_20161225_1719'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zhuditable',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='zuxuntable',
            options={'ordering': ['-pk']},
        ),
    ]
