# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0008_auto_20170102_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='zhuditable',
            name='time_stamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
