# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 00:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0009_zhuditable_time_stamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zhuditable',
            name='img3',
        ),
    ]
