# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-05 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('SSART', '隊員'), ('AS', '替代役')], max_length=20)),
                ('rank', models.CharField(max_length=20)),
            ],
        ),
    ]
