# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-05 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20161105_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='rank',
            field=models.CharField(choices=[('隊員', '隊員'), ('替代役', '替代役')], max_length=20),
        ),
    ]
