# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-06 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20161105_0331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('rank', models.CharField(choices=[('隊員', '隊員'), ('替代役', '替代役')], max_length=20)),
            ],
        ),
    ]
