# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-11 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_delete_payee'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
