# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-12 01:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_auto_20161111_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('members', django.db.models.manager.Manager()),
            ],
        ),
    ]
