# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-12 02:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_auto_20161112_0950'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
            ],
        ),
    ]
