# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-15 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0009_auto_20161112_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='emergency_call',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='home_phone',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mobile_phone',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
