# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-15 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0010_auto_20161115_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='emergency_call',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='home_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
