# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-22 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0011_auto_20161115_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='eat',
            field=models.BooleanField(default=True),
        ),
    ]
