# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0012_userprofile_eat'),
    ]

    operations = [
        migrations.AddField(
            model_name='payee',
            name='identity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
