# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-02 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clean', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleanmonth',
            name='identify',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
