# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-17 03:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tablemoney', '0049_auto_20161117_1127'),
        ('userprofile', '0011_auto_20161115_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('work_day_count', models.PositiveIntegerField(default=0)),
                ('date', models.ManyToManyField(to='holiday.Date')),
            ],
        ),
        migrations.CreateModel(
            name='HolidayMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('holiday_count', models.PositiveIntegerField(default=0)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablemoney.Month')),
                ('name', models.ManyToManyField(through='holiday.Holiday', to='userprofile.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='holiday',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='holiday.HolidayMonth'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.UserProfile'),
        ),
    ]
