# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-19 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0007_auto_20161118_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='one',
            field=models.BooleanField(default=False),
        ),
    ]
