# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-20 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0011_auto_20161120_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='date',
            field=models.ManyToManyField(default=1, to='holiday.Date'),
        ),
    ]
