# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-21 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0013_auto_20161120_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='work_day_count',
            field=models.CharField(default='尚未排假', max_length=20),
        ),
    ]
