# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-21 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0014_auto_20161121_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='date',
            field=models.ManyToManyField(blank=True, to='holiday.Date'),
        ),
    ]
