# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-21 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0018_auto_20161121_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='identify',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
