# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-22 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0020_auto_20161122_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holiday',
            name='date',
        ),
        migrations.AddField(
            model_name='holiday',
            name='date',
            field=models.ManyToManyField(blank=True, to='holiday.Date'),
        ),
    ]
