# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-23 00:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0023_auto_20161122_1352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holidaymonth',
            options={'ordering': ['-pk']},
        ),
    ]
