# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-29 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0024_auto_20161123_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='work_day_count',
            field=models.CharField(max_length=20),
        ),
    ]
