# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-29 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0025_auto_20161129_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='work_day_count',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
