# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-06 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0026_auto_20161129_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidaymonth',
            name='month',
            field=models.CharField(max_length=20),
        ),
    ]
