# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-06 02:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0029_holiday_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holiday',
            name='test',
        ),
    ]
