# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-06 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0030_remove_holiday_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='one',
            field=models.BooleanField(default=False),
        ),
    ]
