# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-06 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0032_auto_20161206_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holiday',
            name='eighteenth',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='eighth',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='eleventh',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='fifteenth',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='fifth',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='first',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='fourteenth',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='fourth',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='nineteenth',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='ninth',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='second',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='seventeenth',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='seventh',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='sixteenth',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='sixth',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='tenth',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='third',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='thirteenth',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='thirtieth',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='thirty_first',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='twelfth',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='twentieth',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='twenty_eighth',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='twenty_fifth',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='twenty_first',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='twenty_fourth',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='twenty_ninth',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='twenty_second',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='twenty_seventh',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='twenty_sixth',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='twenty_third',
        ),
        migrations.AlterField(
            model_name='holiday',
            name='date',
            field=models.ManyToManyField(blank=True, null=True, to='holiday.Date'),
        ),
    ]
