# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-06 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0033_auto_20161206_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='date',
            field=models.ManyToManyField(blank=True, to='holiday.Date'),
        ),
    ]
