# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-07 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0034_auto_20161206_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='holiday_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
