# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 07:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import holiday.models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0012_userprofile_eat'),
        ('holiday', '0035_holiday_holiday_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayFromDocx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('date', models.CharField(max_length=1000)),
                ('work_day_count', models.CharField(blank=True, max_length=20)),
                ('holiday_count', models.PositiveIntegerField(default=0)),
                ('identify', models.CharField(max_length=20)),
                ('holiday_file', models.FileField(upload_to=holiday.models.upload_location)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='holiday.HolidayMonth')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.UserProfile')),
            ],
        ),
    ]
