# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 07:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0036_holidayfromdocx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidayfromdocx',
            name='date',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='holidayfromdocx',
            name='identify',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='holidayfromdocx',
            name='month',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='holiday.HolidayMonth'),
        ),
        migrations.AlterField(
            model_name='holidayfromdocx',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.UserProfile'),
        ),
        migrations.AlterField(
            model_name='holidayfromdocx',
            name='year',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
