# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 07:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0037_auto_20170218_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidayfromdocx',
            name='month',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='holiday.HolidayMonth'),
        ),
        migrations.AlterField(
            model_name='holidayfromdocx',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.UserProfile'),
        ),
        migrations.AlterField(
            model_name='holidayfromdocx',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
