# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0039_auto_20170218_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidayfromdocx',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userprofile.UserProfile'),
            preserve_default=False,
        ),
    ]
