# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import holiday.models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0040_auto_20170218_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayMonthFromDocx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=20)),
                ('holiday_file', models.FileField(upload_to=holiday.models.upload_location)),
            ],
        ),
    ]
