# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0042_remove_holidayfromdocx_holiday_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidaymonthfromdocx',
            name='holiday_json',
            field=models.CharField(default=1, max_length=999999999),
            preserve_default=False,
        ),
    ]
