# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 23:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0043_holidaymonthfromdocx_holiday_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holidaymonthfromdocx',
            name='holiday_json',
        ),
    ]
