# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0044_remove_holidaymonthfromdocx_holiday_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidayfromdocx',
            name='work_day_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
