# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 23:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0045_auto_20170219_0722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holidayfromdocx',
            name='holiday_count',
        ),
    ]
