# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 23:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0046_remove_holidayfromdocx_holiday_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidayfromdocx',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='holiday.HolidayMonthFromDocx'),
        ),
    ]
