# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 07:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0047_auto_20170219_0742'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holidaymonthfromdocx',
            options={'ordering': ['-pk']},
        ),
    ]
