# """
# Django settings for ssarthl01 project.
#
# Generated by 'django-admin startproject' using Django 1.9.11.
#
# For more information on this file, see
# https://docs.djangoproject.com/en/1.9/topics/settings/
#
# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/1.9/ref/settings/
# """
#
# import os
#
# # Build paths inside the project like this: os.path.join(BASE_DIR, ...)
# BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
#
#
# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/
#
# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'uw)mivp6qk#6yfo1w6azy!60fs=!cwy3nc@@e-6%*rl=v9$kjr'
#
# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = False
#
# ALLOWED_HOSTS = ["ssarthl01.herokuapp.com",]
#
#
# # Application definition
#
# INSTALLED_APPS = [
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
#
#
#     'widget_tweaks',
#     'storages',
#
#
#     'userprofile',
#     'tablemoney',
#     'holiday',
#     'train',
#     'clean',
# ]
#
# MIDDLEWARE_CLASSES = [
#     'django.middleware.security.SecurityMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
#     'whitenoise.middleware.WhiteNoiseMiddleware',
# ]
#
# ROOT_URLCONF = 'ssarthl01.urls'
#
# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [os.path.join(BASE_DIR, 'templates')],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.debug',
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]
#
# WSGI_APPLICATION = 'ssarthl01.wsgi.application'
#
#
# # Database
# # https://docs.djangoproject.com/en/1.9/ref/settings/#databases
#
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }
#
# import dj_database_url
# db_from_env = dj_database_url.config()
# DATABASES['default'].update(db_from_env)
#
#
# # Password validation
# # https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators
#
# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]
#
#
# # Internationalization
# # https://docs.djangoproject.com/en/1.9/topics/i18n/
#
# LANGUAGE_CODE = 'en-us'
#
# TIME_ZONE = 'Asia/Hong_Kong'
#
# USE_I18N = True
#
# USE_L10N = True
#
# USE_TZ = True
#
#
# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/1.9/howto/static-files/
#
#
#
# # 可以放公用的static，例如custom css 用 collect static就會被複製進STATIC_ROOT
# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, "custom_static")
#     #'/var/www/static/',
# ]
# # 真的使用的檔案
# STATIC_ROOT = os.path.join(BASE_DIR, "static")
#
#
# AWS_STORAGE_BUCKET_NAME = 'ssarthl01'
# AWS_ACCESS_KEY_ID = 'AKIAIAFGNY7EP76GJRAQ'
# AWS_SECRET_ACCESS_KEY = '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'
# # Tell django-storages that when coming up with the URL for an item in S3 storage, keep
# # it simple - just use this domain plus the path. (If this isn't set, things get complicated).
# # This controls how the `static` template tag from `staticfiles` gets expanded, if you're using it.
# # We also use it in the next setting.
# AWS_S3_CUSTOM_DOMAIN = 's3.amazonaws.com/%s' % AWS_STORAGE_BUCKET_NAME
# # This is used by the `static` template tag from `static`, if you're using that. Or if anything else
# # refers directly to STATIC_URL. So it's safest to always set it.
# STATIC_URL = "https://%s/" % AWS_S3_CUSTOM_DOMAIN
# # Tell the staticfiles app to use S3Boto storage when writing the collected static files (when
# # you run `collectstatic`).
#
#
#
# STATICFILES_LOCATION = 'static'
# STATICFILES_STORAGE = 'custom_storages.StaticStorage'
# STATIC_URL = "https://%s/%s/" % (AWS_S3_CUSTOM_DOMAIN, STATICFILES_LOCATION)
#
# MEDIA_ROOT = os.path.join(BASE_DIR, "media")
# MEDIAFILES_LOCATION = 'media'
# MEDIA_URL = "https://%s/%s/" % (AWS_S3_CUSTOM_DOMAIN, MEDIAFILES_LOCATION)
# DEFAULT_FILE_STORAGE = 'custom_storages.MediaStorage'
#
#
# LOGIN_URL='/login/'
# LOGIN_REDIRECT_URL='/login/'
#
#
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_HOST_USER = 'miwooro@gmail.com' #my gmail username
# EMAIL_HOST_PASSWORD = '7shi6A1Fer7ye' #my gmail password
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# DEFAULT_FROM_EMAIL = "miwooro <miwooro@gmail.com>"
#
#
# ADMINS = [('miwooro', EMAIL_HOST_USER)]
# MANAGERS = ADMINS
